- name: Replace Zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: "{{zookeeper.config_file}}"
    mode: 0400
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"

- name: Replace Broker server.properties
  template:
    src: server.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"

- name: Replace in zookeeper.properties
  lineinfile:
    path: "{{zookeeper.config_file}}"
    regexp: '^server.{{zookeeper_id}}={{zookeeper_ip}}:2888:3888'
    line: 'server.{{zookeeper_id}}={{zookeeper_ip}}:2888:3888'